export const TITLES_EL_IF_TECH_DELIVERY_PRODUCTS_IN_STORES = {
  title: 'Products in stores',
  refresh: 'Refresh',
  create: 'Add a new product in store',
  createConfirmTitle: 'Add a new product in store?',
  messageSuccessCreate: 'New product in store successfully added',
  update: 'Edit product in store details',
  messageSuccessUpdate: 'Product in store details successfully updated',
  updateConfirmTitle: 'Update product in store details?',
  remove: 'Deleting the product in store',
  messageSuccessRemove: 'Product in store data successfully deleted',
  removeConfirmTitle: 'Delete product in store data?',
  store: 'Store',
  product: 'Product',
  category: 'Category',
  image: 'Image',
  mutationDate: 'Mutation date',
  stringValidateMin: 'Must be at least ${min} characters',
  stringValidateMax: 'Must be ${max} characters or less',
  stringValidateEmpty: 'Required'
};
